### ISSUE TITLE
possible new implementation?

### ISSUE THREAD

**Issue by safareli** [puffnfresh/daggy#7]
I have implemented something like daggy [here](https://github.com/safareli/free/blob/dev/src/union.js)

how is it different?:
- Instead of constructor Functions it uses `Object.create`
- when sum type is created it returns type representative and you can call it as it's just an object
- values used to create object is stored as array and there is no need to allocate  new array in cata
- type definition is stored in type representative and it allows to have only one `cata` and `toString`s

I believe it has a bit better performance too. would like to hear what others think.

**Comment by safareli** [comment]
ping @puffnfresh @SimonRichardson

**Comment by SimonRichardson** [comment]
I'll check on Monday if that's ok 😀

**Comment by safareli** [comment]
np :P

**Comment by SimonRichardson** [comment]
I'm fine with this, it would be good if we can move `sanctuary-type-classes` to `fantasy-sorcery`, otherwise this seems like it's a good start.

@puffnfresh you mind if we do a radical thing like this, I'm more than happy for it to move forward!

**Comment by puffnfresh** [comment]
Don't mind.

Irrelevant; but can it be typed with TypeScript?

**Comment by safareli** [comment]
> I'm fine with this, it would be good if we can move sanctuary-type-classes to fantasy-sorcery, otherwise this seems like it's a good start.

/cc @davidchambers

> Irrelevant; but can it be typed with TypeScript?

If you are asking about:
- sanctuary-type-classes, i think it's somehow possible.
- about this implementations, I think no.


What would be the best way to move forward on this?
1. create PR here (it will be a breaking change)
2. create new repo in FL and create PR there
3. move `daggy` to FL and do `1.`

---

btw there is also a related work [sanctuary-union-type](https://github.com/sanctuary-js/sanctuary-union-type) and @JAForbes[/sum-type](https://github.com/JAForbes/sum-type) which started as using `sanctiary-def` for type ckecking on @paldepind[/union-type](https://github.com/paldepind/union-type)

**Comment by SimonRichardson** [comment]
Question how does a typed union work with types i.e. `F A -> B` do you have to define new union types when this happens? I have no idea, some link to code would be amazing :) Really interested!

**Comment by safareli** [comment]
@SimonRichardson I think I didn't understand your question, if you want some example of union
here is [Par](https://github.com/safareli/free/blob/dev/src/par.js#L5-L13), [Seq](https://github.com/safareli/free/blob/dev/src/seq.js#L5-L12), [Concurrent](https://github.com/safareli/free/blob/dev/src/concurrent.js#L16-L25) from some from my free.

**Comment by SimonRichardson** [comment]
I was on about type checking versions and how it knows what to type check when you've provided a `chain` for example.

**Comment by safareli** [comment]
ah, I think @davidchambers is the one who can answer that question :P

**Comment by SimonRichardson** [comment]
@safareli I vote we go for it, we can clean up as we go a long, nothings perfect, we just need forward momentum!

**Comment by safareli** [comment]
> What would be the best way to move forward on this?
> 1. create PR here (it will be a breaking change)
> 2. create new repo in FL and create PR there (then create a note here about new implementation)
> 3. move `daggy` to FL and do `1.`

@SimonRichardson

**Comment by SimonRichardson** [comment]
Move daggy to FL and do 1 imo

**Comment by safareli** [comment]
ok will open PR here then, we can move it later too.
